CREATE TABLE ALBUMS (
    ID SERIAL PRIMARY KEY,
    ALBUM_NAME TEXT NOT NULL,
    LIST TEXT NOT NULL,
    USER_ID INT NOT NULL,
    CONSTRAINT fk_Albums  
    FOREIGN KEY(USER_ID)   
    REFERENCES USERS(ID)  
);