CREATE TABLE BLOGS (
    ID SERIAL PRIMARY KEY,
    PUBLISHED_DATE DATE NOT NULL,
    TITLE TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    GROUPS TEXT NOT NULL,
    USER_ID INT NOT NULL,
    CONSTRAINT fk_Blogs  
    FOREIGN KEY(USER_ID)   
    REFERENCES USERS(ID)  
);